name: Check Pull-Request

on:
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    # pull_request event is required only for autolabeler
    types: [opened, reopened, synchronize]

jobs:
  danger-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - name: Run Danger JS
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

  # Dependency Review Action
  #
  # This Action will scan dependency manifest files that change as part of a Pull Reqest, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
  #
  # Source repository: https://github.com/actions/dependency-review-action
  # Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
  dependency-review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1

  labeler:
    name: labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: 'Pull request labeler'
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

  auto_labeler:
    name: auto-label
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    permissions:
      contents: read
      pull-requests: write # for release-drafter/release-drafter to add label to PR
    steps:
      - name: 'Pull request auto-labeler'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
